### PR TITLE
Test against Ruby 2.3.0

### PR DESCRIPTION
**Pull request by tricknotes**
It works fine for me :sunny:

### CODE REVIEW

**Comment by koic** [comment]
Test has failed :crying_cat_face: 
Maybe it fixed by adding to `.travis.yml` like this:

```yaml
before_install: gem update bundler
```

Thanks.

**Comment by tricknotes** [comment]
Oops, I missed it.Thanks @koic .
Now I pushed it as 5516ee2

**Comment by koic** [comment]
Thank you for your quick response :ok_woman:

**Comment by tricknotes** [comment]
thanks for your kindness :sparkles:

**Pull request merged**
